name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Executa uma vez por dia à meia-noite UTC
  workflow_dispatch:  # Permite execução manual do workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update GitHub Stats
        run: |
          curl -o README.md "https://github-readme-stats.vercel.app/api/top-langs/?username=dnribeiro&layout=donut&theme=dark&count_private=true&token=${{ secrets.GH_STATS_TOKEN }}"
      
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated GitHub Stats" || echo "No changes to commit"
          git push
