name: Update README stats

on:
  schedule:
    - cron: '0 */12 * * *'  # Roda a cada 12 horas
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          # Aqui você pode usar um script para atualizar o README
          # O token estará disponível como variável de ambiente
